### ISSUE TITLE
Yellow Theme: Text is unreadable. Need more contrast.

### ISSUE THREAD

**Issue by jspreddy** [GwtMaterialDesign/gwt-material-themes#16]
The text in the **Yellow Theme** is unreadable. It is essentially **light text** on **light background**. We need more contrast for this. Possibly a darker text (black tones) would be better for this theme.

![gwt_material_design](https://cloud.githubusercontent.com/assets/2302194/24373133/5ca5937a-12fe-11e7-993f-311196a61a8c.jpg)

**Comment by kevzlou7979** [comment]
This can be possibly done with user options (to set manually the text color) - It is not nice, if we override the default text / link / icon color that will be set into the``` materialize.yellow.css``` which causes some override issue because of the text / link / icon color. So in short let the user set manually the text color. We did a callback function to configure that out but for demo purpose we will get rid of this.
